services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # api:
  #   build: ./backend
  #   restart: always
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_PORT: ${POSTGRES_PORT}
  #     PORT: ${PORT}
  #   depends_on:
  #     - db
  #   ports:
  #     - '${PORT}:8000'
  #   volumes:
  #     - .:/backend/app
volumes:
  postgres_data:
